@SortingGame_HostAddress = http://localhost:5010

GET {{SortingGame_HostAddress}}/weatherforecast/
Accept: application/json
###
POST {{SortingGame_HostAddress}}/customer/35554/score/0.2
Accept: application/json
###
GET {{SortingGame_HostAddress}}/leaderboard?start=1&end=1
Accept: application/json
###
GET {{SortingGame_HostAddress}}/74724?low=1&high=2
Accept: application/json